### ISSUE TITLE
Distinguish between "conceptual SCT" and "over-the-wire" SCT

### ISSUE THREAD

**Issue by eranmes** [SabaEskandarian/cert_trans_priv#3]
My original comment:
There are two kinds of SCTs: The “conceptual” SCT and the “transmitted” SCT, which is what gets embedded in the certificate itself. Worth reconciling the two, at the very least discussing the order of signatures: i.e. the signature in the “transmitted” SCT (described in RFC6962) must be over the entire thing, so signing everything else that goes into the SCT should happen first.

To which Seba replied:
Some of the additional things that are being sent may cause some circular dependency problems if they’re inside the SCT. for example, the signed hash of the SCT, if placed inside the SCT, would cause the SCT to change and render the hash inaccurate. Is there a practical way to send the additional signed information alongside the SCT? Otherwise the signed hash could be just of the parts of the SCT mentioned in the RFC and not our additions

**Comment by eranmes** [comment]
There’s no way to send un-signed data alongside the SCT. However, it seems to me (please confirm) that we can have (H(s), Sig k H (H(s))) and (t + H(s), Sig k T (t + H(s))) inside the SCT mentioned in the RFC by calculating them first, putting them in the SCT extensions field, *then* calculating Sig k S over the whole thing, right? That’s based on my understanding that the “important” bit, denoted ‘s’ in Definition 4, is just the combination of the certificate (denoted  ‘m’) and the timestamp (denoted ‘t’), is that correct? If that is not the case, we could still work around that by signing twice using k_S, once signing (conceptual SCT) ‘s = (m, t)’, embedding that signature, together with the other two, in the “RFC SCT” extensions field, then signing the whole thing with k_S.
If my understanding is correct (and we don’t have to do the work-around I described), then I suggest re-ordering the bullets in Definition 4 such that Sig k S (s + other hashes, signatures) is produced last.

**Comment by SabaEskandarian** [comment]
That's absolutely right. I changed the bullet order. Thanks for pointing out that this is not really an issue.
