### ISSUE TITLE
Replace 't' with a different identifier in section 4.1.

### ISSUE THREAD

**Issue by eranmes** [SabaEskandarian/cert_trans_priv#6]
In Section 4.1., describing the construction for the mechanism to have private domain names hidden in CT, 't' is used to denote the output on the VRF on the private label:
$(t, \pi)=Eval_{sk_\nu}(d||s)$
Since 't' is used to denote the timestamp in the previous section, I suggest changing it to something different, maybe 'l'?

**Comment by SabaEskandarian** [comment]
changed to tk for token
